@host = http://localhost:5004

GET {{host}}/tasks
Accept: application/json

###

GET {{host}}/tasks/1
Accept: application/json

###

POST {{host}}/tasks
Content-Type: application/json

{
    "name": "Новая задача",
    "status": 0
}
###

PUT {{host}}/tasks/1
Content-Type: application/json

{
    "name": "Изучить Web API - ГОТОВО",
    "status": 0
}
###

DELETE {{host}}/tasks/1

###
POST {{host}}/tasks
Content-Type: application/json

{
    "name": "",
    "status": 0
}
###

POST {{host}}/auth/login
Content-Type: application/json

{
    "login": "admin",
    "password": "1234"
}
###

POST {{host}}/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJleHAiOjE3ODIwNDg5NDUsImlzcyI6IlRhc2tNYW5hZ2VyQXBpIn0.xA3HW0iNt4XZCQW3-BSHuEQ9vlFZOL0myxC_ID5SSS0

{
    "name": "Задача с токеном",
    "status": 0
}